[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "moss-tts-nano"
version = "0.1.0"
description = "Open-source realtime multilingual tiny TTS from OpenMOSS."
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "OpenMOSS Team" },
]
dependencies = [
  "numpy>=2.4.4",
  "fastapi>=0.135.3",
  "python-multipart>=0.0.26",
  "sentencepiece>=0.2.1",
  "torch==2.11.0",
  "torchaudio==2.11.0",
  "transformers==5.5.4",
  "uvicorn>=0.44.0",
]

[project.urls]
Homepage = "https://github.com/OpenMOSS/MOSS-TTS-Nano"
Repository = "https://github.com/OpenMOSS/MOSS-TTS-Nano"
Documentation = "https://studio.mosi.cn/docs/moss-tts-nano"

[project.scripts]
moss-tts-nano = "moss_tts_nano.cli:main"

[tool.setuptools]
packages = ["moss_tts_nano"]
py-modules = [
  "app",
  "infer",
  "moss_tts_nano_runtime",
  "text_normalization_pipeline",
  "tts_robust_normalizer_single_script",
]
